# Generated by Django 4.2.30 on 2026-08-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome or SVG icon identifier, e.g., 'fa-parking'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(help_text='City / Area name, e.g. Solapur, Pune', max_length=100)),
                ('address', models.TextField()),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Commercial', 'Commercial')], default='House', max_length=50)),
                ('purpose', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], default='Sale', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in sq.ft', max_digits=10)),
                ('parking', models.BooleanField(default=True, help_text='Has parking facility')),
                ('furnished', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], default='Semi Furnished', max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Rented', 'Rented')], default='Available', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='properties/videos/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
