# Generated by Django 4.2.30 on 2026-08-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DREAM HOMES', max_length=100)),
                ('tagline', models.CharField(default='REAL ESTATE ADVISORY • RERA CERTIFIED', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='info@dreamhomes.com', max_length=254)),
                ('address', models.CharField(default='101 Prime Plaza, VIP Road, Pune & Solapur, Maharashtra', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
