# Generated by Django 4.2.30 on 2026-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_founder_name',
            field=models.CharField(default='Dnyaneshwar Melage', help_text='Founder Name', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_quote',
            field=models.CharField(default='Your property, our responsibility.', help_text='Highlighted tagline quote on About page', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_subtitle',
            field=models.CharField(default='Leading real estate consultancy delivering trust, transparency, and top-tier properties since 2010.', help_text='Subtitle on top of About page', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision_heading',
            field=models.CharField(default='Redefining Property Advisory', help_text='Heading for story section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision_text',
            field=models.TextField(default='Founded by Dnyaneshwar Melage, Dream Homes is a premier real estate consultancy dedicated to helping buyers, sellers, and investors navigate property decisions with trust, transparency, and expert market intelligence.', help_text='Main description text on About page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(default='101 Prime Plaza, VIP Road, Solapur - 413001, Maharashtra', help_text='Full address for contact page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours',
            field=models.CharField(default='Monday - Saturday: 9:00 AM - 7:00 PM', help_text='Working hours', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle',
            field=models.CharField(default='Have questions or want to discuss property investments? Send us a message or visit our office.', help_text='Subtitle on top of Contact page', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(default='https://maps.google.com/maps?q=101+Prime+Plaza+VIP+Road+Solapur+Maharashtra&t=&z=15&ie=UTF8&iwloc=&output=embed', help_text='Google Maps Embed URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='dhairyashilmelage@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+91 7083150302', max_length=50),
        ),
    ]
