# Generated by Django 4.2.30 on 2026-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_sitesettings_about_founder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_vision_text',
            field=models.TextField(default='Founded by Dnyaneshwar Melage, Perfect Homes is a premier real estate consultancy dedicated to helping buyers, sellers, and investors navigate property decisions with trust, transparency, and expert market intelligence.', help_text='Main description text on About page'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='PERFECT HOMES', max_length=100),
        ),
    ]
