# Generated by Django 4.2.30 on 2026-09-03 08:01

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_sitesettings_about_vision_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Direct Cloudinary, YouTube, or MP4 video URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=properties.models.select_video_storage, upload_to='properties/videos/'),
        ),
    ]
